USE suco_vendas;
INSERT INTO [TABELA DE VENDEDORES]([MATRICULA],[NOME],[PERCENTUAL COMISSAO])
VALUES('00235','Márcio Almeida Silva',0.08);

INSERT INTO [TABELA DE VENDEDORES]([MATRICULA],[NOME],[PERCENTUAL COMISSAO])
VALUES('00236','Cláudia Morais',0.08)